# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mach7 < Formula
  desc "macOS system tuning, telemetry, and benchmark TUI"
  homepage "https://github.com/Diiplexus/MACH7"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Diiplexus/MACH7/releases/download/v0.1.0/mach7_0.1.0_darwin_amd64.tar.gz"
    sha256 "b3f8ecdafd9c32712a267894c113b4eb84200d01b170397381d21c020507c91a"

    define_method(:install) do
      bin.install "mach7"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Diiplexus/MACH7/releases/download/v0.1.0/mach7_0.1.0_darwin_arm64.tar.gz"
    sha256 "2a40ceeab23a9669418f6809f4623c25da72d4543e3e628337e98f1c14ac083b"

    define_method(:install) do
      bin.install "mach7"
    end
  end

  test do
    system "#{bin}/mach7", "--help"
  end
end
